problems:
  -
    q: "5+5"
    a: ["10","ten","десять"]
    v: ["10","ten","десять","1O"]
  -
    q: "7+3"
    a: ["10"]
  -
    q: "1+1"
    a: ["2","два","two"]
    v: ["2","11","два","two"]
  -
    q: "8+3"
    a: ["eleven","11","одиннадцать"]
    v: ["eleven","11","одиннадцать","5"]
  -
    q: "1+2"
    a: ["3"]
        